version: '3'
  
  services:
    app:
      build: .
      ports:
        - '3000:3000'
      environment:
        - NODE_ENV=production
        - MONGODB_URI=mongodb://mongo:27017/blog-task-api
      depends_on:
        - mongo
      restart: unless-stopped
  
    mongo:
      image: mongo:6
      ports:
        - '27017:27017'
      volumes:
        - mongo_data:/data/db
      restart: unless-stopped
  
  volumes:
    mongo_data: